version: '3'
services:
  mysql:
    image: mysql:5.6
    container_name: mydb-mysql1
    environment:
    - MYSQL_ROOT_PASSWORD=db1234
    - MYSQL_DATABASE=demodb
    volumes:
    - mysqldata:/var/lib/mysql
  backend:
    image: 769585693008.dkr.ecr.us-east-2.amazonaws.com/backendrepo:latest
    depends_on:
    - mysql
    links:
    - mysql
  frontend:
    image: 769585693008.dkr.ecr.us-east-2.amazonaws.com/frontend:latest
    container_name: frontendcontainer
    depends_on:
    - backend
    ports:
    - 80:80
volumes:
  mysqldata:
